language: node_js
sudo: required
node_js:
  - lts/*
cache:
  npm: false

stages:
  - name: build
  - name: deploy
    if: branch IN (dev, canary, rc)
  - name: trigger_canary
    if: branch = canary

before_install:
  - if [ "$TRAVIS_BRANCH" != "dev" ]; then mv console/env-production console/.env; else mv console/env-development console/.env; fi
  # Include bintray if branch is dev, canary or rc
  - if echo "dev canary rc" | grep "$TRAVIS_BRANCH"; then echo "@terminusdb:registry=https://api.bintray.com/npm/terminusdb/npm-$TRAVIS_BRANCH" > $TRAVIS_BUILD_DIR/.npmrc; fi

before_deploy:
  - mv console/env-production console/.env

jobs:
  include:
    - stage: build
      script:
        - npm run build

    - stage: deploy
      script:
        - npm run build
        - bash ".ci/publish_$TRAVIS_BRANCH.sh"

    - stage: trigger_canary
      script:
        - bash .ci/trigger_canary.sh

deploy:
  - provider: npm
    registry: "https://registry.npmjs.org/"
    skip_cleanup: true
    access: public
    email: "robin@datachemist.com"
    api_key: $NPM_TOKEN
    keep_history: true
    auth_method: "authToken"
    on:
      branch: master
      tags: true

