language: node_js
sudo: required
node_js:
  - lts/*

stages:
  - build
  - name: deploy_dev
    if: branch = dev

jobs:
  include:
    - stage: build
      script:
        - npm run build

    - stage: deploy_dev
      script:
        - npm run build
        - bash .ci/publish_dev.sh

branches:
  only:
    - dev
    - master

deploy:
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash public_pages.sh
    on:
      tags: true
  - provider: npm
    registry: "https://registry.npmjs.org/"
    skip_cleanup: true
    access: public
    email: "francesca@datachemist.com"
    api_key: $NPM_TOKEN
    keep_history: true
    auth_method: "authToken"
    on:
      branch : master
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*

